name: Check

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v4

  format:
    needs: [ validation ]
    name: Verify Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialization
        uses: ./.github/actions/init

      - name: Check format
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: ktlintCheck

      - name: Check code style
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: detekt

  build:
    needs: [ validation, format ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Initialization
        uses: ./.github/actions/init
        with:
          jdk: 17

      - name: Build
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: assemble

      - name: Test
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: test
