name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.pull_request.user.login != 'renovate[bot]'

    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Initialization
        uses: ./.github/actions/init
        with:
          jdk: 17

      - name: Check code style
        uses: gradle/actions/setup-gradle@v4
        env:
          DETEKT_IGNORE_FAILURES: true
        with:
          arguments: detekt

      - name: Build
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: assemble

      - name: Test
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: test

      - name: Generate test report
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: koverXmlReport

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
